# Generated by Django 2.0.2 on 2018-02-03 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('score', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('home_goals', models.IntegerField(default=None)),
                ('away_goals', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Game'),
        ),
        migrations.AddField(
            model_name='bet',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
