# Generated by Django 2.0.2 on 2018-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
