# Generated by Django 2.0.2 on 2018-02-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180203_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='gameid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='score',
        ),
    ]
