# Generated by Django 2.0.2 on 2018-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180203_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
