# Generated by Django 2.0.2 on 2018-02-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180214_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
