# Generated by Django 2.0.2 on 2018-02-18 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_userstoleagues'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstoleagues',
            unique_together={('user', 'league')},
        ),
    ]
