# Generated by Django 2.0.2 on 2018-03-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180218_0104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstoleagues',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userstoleagues',
            name='league',
        ),
        migrations.RemoveField(
            model_name='userstoleagues',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsersToLeagues',
        ),
    ]
