# Generated by Django 2.0.2 on 2018-03-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_created_userstoleagues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstoleagues',
            name='league',
        ),
        migrations.RemoveField(
            model_name='userstoleagues',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsersToLeagues',
        ),
    ]
